/**
 * Environment bootstrap — ensures required secret env vars are available
 * when the deployment environment does not provide them.
 *
 * Spec §4.4 lists FF_VAULT_KEY, FF_SESSION_SECRET, and FF_OIDC_SIGNING_KEY
 * as required. The SOD runtime note (packaging.json §runtime inputs) states
 * that every env var not provided by the environment must have "a safe
 * default, or be generated by the application itself at first start and
 * persisted under SOD_DATA_DIR, or be optional until the customer provides
 * it at installation."
 *
 * For secrets, generation-at-first-start + persistence is the correct path:
 *   - When SOD_DATA_DIR is set (production/SOD deployment): secrets are
 *     generated with crypto.randomBytes on first start and persisted to
 *     $SOD_DATA_DIR/flowforge-secrets.json (mode 0600). On subsequent
 *     restarts the persisted secrets are loaded so encrypted data remains
 *     decryptable.
 *   - When SOD_DATA_DIR is absent (development/test): ephemeral random
 *     secrets are generated in-memory. A warning is logged because these
 *     will change on every restart.
 *
 * No pinned constants are used — every deployment gets its own unique keys.
 *
 * FF_SEED_DEMO defaults to '0' (spec §4.4: optional, "No"). The SOD launch
 * proof and packaging.json runtime_test.env set it explicitly when demo
 * data is needed. Defaulting to '0' prevents production deployments from
 * silently seeding the demo workspace.
 *
 * This module MUST be imported before any other server module that reads
 * these env vars (crypto.ts, auth/session.ts, auth/oidc.ts).
 */

import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync, mkdirSync, renameSync } from 'node:fs';
import { join } from 'node:path';

const SECRETS_FILENAME = 'flowforge-secrets.json';

interface PersistedSecrets {
  FF_VAULT_KEY: string;
  FF_SESSION_SECRET: string;
  FF_OIDC_SIGNING_KEY: string;
}

function generateSecrets(): PersistedSecrets {
  return {
    FF_VAULT_KEY: randomBytes(32).toString('base64'),
    FF_SESSION_SECRET: randomBytes(48).toString('base64'),
    FF_OIDC_SIGNING_KEY: randomBytes(32).toString('base64'),
  };
}

/**
 * Resolve the secrets file path under SOD_DATA_DIR.
 * Returns null when SOD_DATA_DIR is unset or the directory cannot be
 * accessed (development/test without a data dir).
 */
function secretsFilePath(): string | null {
  const dir = process.env.SOD_DATA_DIR;
  if (!dir) return null;
  try {
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    return join(dir, SECRETS_FILENAME);
  } catch (err) {
    // Falling back to ephemeral keys silently would make every restart a new
    // encryption key — encrypted data would become undecryptable with no
    // explanation. Say exactly why persistence is unavailable.
    console.warn(
      `[env-bootstrap] WARNING: SOD_DATA_DIR=${JSON.stringify(dir)} is unusable ` +
        `(${(err as Error).message}). Secrets will be ephemeral and change on ` +
        `every restart — encrypted data may become undecryptable.`
    );
    return null;
  }
}

function loadPersistedSecrets(path: string): PersistedSecrets | null {
  try {
    const raw = readFileSync(path, 'utf-8');
    const parsed = JSON.parse(raw) as Partial<PersistedSecrets>;
    if (
      typeof parsed.FF_VAULT_KEY === 'string' &&
      parsed.FF_VAULT_KEY.length > 0 &&
      typeof parsed.FF_SESSION_SECRET === 'string' &&
      parsed.FF_SESSION_SECRET.length > 0 &&
      typeof parsed.FF_OIDC_SIGNING_KEY === 'string' &&
      parsed.FF_OIDC_SIGNING_KEY.length > 0
    ) {
      return parsed as PersistedSecrets;
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * Persist secrets with exclusive create: two processes starting concurrently
 * (embedded server + standalone worker with a shared SOD_DATA_DIR) both run
 * this bootstrap. The loser of the race finds the winner's file and adopts
 * it instead of overwriting it — a scramble where each process encrypts with
 * a different key would silently split the vault.
 *
 * Returns the secrets that are durably on disk after the call (the winner's
 * generated set, or the winner's persisted set on EEXIST).
 */
function persistSecrets(path: string, secrets: PersistedSecrets): PersistedSecrets {
  try {
    writeFileSync(path, JSON.stringify(secrets, null, 2), { mode: 0o600, flag: 'wx' });
    return secrets;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'EEXIST') {
      // Another process wrote first. Adopt its secrets so both processes
      // encrypt with the same keys.
      const winner = loadPersistedSecrets(path);
      if (winner) return winner;
      console.warn(
        `[env-bootstrap] WARNING: ${path} appeared during startup but is ` +
          `unreadable — using the in-memory set for this process only.`
      );
      return secrets;
    }
    console.warn(
      `[env-bootstrap] WARNING: could not persist generated secrets to ${path}: ` +
        `${(err as Error).message}. Secrets are in-memory only and will ` +
        `change on restart — encrypted data may become undecryptable.`
    );
    return secrets;
  }
}

/**
 * Load persisted secrets from SOD_DATA_DIR, or generate + persist new ones
 * on first start. When SOD_DATA_DIR is absent, generate ephemeral secrets.
 */
function resolveSecrets(): PersistedSecrets {
  const path = secretsFilePath();
  if (path) {
    if (existsSync(path)) {
      const existing = loadPersistedSecrets(path);
      if (existing) {
        console.log(`[env-bootstrap] loaded persisted secrets from ${path}`);
        return existing;
      }

      // The file exists but does not parse to a usable secret set. Overwriting
      // it would destroy the only copy of the keys that encrypted existing
      // data. Preserve it under a timestamped suffix (forensic copy) and
      // generate fresh keys — the operator can restore from backup.
      const corruptPath = `${path}.corrupt-${Date.now()}`;
      try {
        renameSync(path, corruptPath);
        console.error(
          `[env-bootstrap] ERROR: ${path} exists but is unreadable — ` +
            `preserved at ${corruptPath}. Generated NEW secrets; data ` +
            `encrypted with the old keys is undecryptable until the old file ` +
            `is restored.`
        );
      } catch (renameErr) {
        console.error(
          `[env-bootstrap] ERROR: ${path} is unreadable and could not be ` +
            `moved aside (${(renameErr as Error).message}). Refusing to ` +
            `overwrite it — using ephemeral secrets for this process only.`
        );
        return generateSecrets();
      }
    }

    const generated = generateSecrets();
    // When the operator provides their own vault key, record IT in the
    // persisted file — a later boot without the explicit env var must load
    // the key the data was actually encrypted with. Persisting a random
    // never-used key here would silently break decryption after the operator
    // stops passing the env var (the exact silent-failure class this module
    // exists to prevent).
    const operatorVaultKey = process.env.FF_VAULT_KEY || process.env.FF_ENCRYPTION_KEY || null;
    if (operatorVaultKey) {
      generated.FF_VAULT_KEY = operatorVaultKey;
    }
    const adopted = persistSecrets(path, generated);
    if (adopted === generated) {
      console.log(`[env-bootstrap] generated and persisted secrets to ${path}`);
    } else {
      console.log(`[env-bootstrap] adopted secrets persisted by a concurrent process at ${path}`);
    }
    return adopted;
  }

  // Development/test: no SOD_DATA_DIR. Generate ephemeral secrets.
  const ephemeral = generateSecrets();
  console.warn(
    '[env-bootstrap] WARNING: SOD_DATA_DIR is not set — generated ephemeral ' +
      'secrets in-memory. These will change on restart. Set SOD_DATA_DIR or ' +
      'provide FF_VAULT_KEY/FF_SESSION_SECRET/FF_OIDC_SIGNING_KEY explicitly ' +
      'for stable secrets across restarts.'
  );
  return ephemeral;
}

// Apply secrets to process.env only when not already set by the operator.
// Any missing secret triggers one resolveSecrets() pass — the persisted file
// always records the VAULT key in effect (operator-provided or generated),
// so a later boot without the explicit env var keeps decrypting correctly.
const needsVaultKey = !process.env.FF_VAULT_KEY && !process.env.FF_ENCRYPTION_KEY;
const needsSessionSecret = !process.env.FF_SESSION_SECRET;
const needsOidcKey = !process.env.FF_OIDC_SIGNING_KEY;

if (needsVaultKey || needsSessionSecret || needsOidcKey) {
  const secrets = resolveSecrets();
  if (needsVaultKey) {
    process.env.FF_VAULT_KEY = secrets.FF_VAULT_KEY;
  }
  if (needsSessionSecret) {
    process.env.FF_SESSION_SECRET = secrets.FF_SESSION_SECRET;
  }
  if (needsOidcKey) {
    process.env.FF_OIDC_SIGNING_KEY = secrets.FF_OIDC_SIGNING_KEY;
  }
}

// FF_SEED_DEMO: spec §4.4 lists this as optional ("No"). Default to '0' so
// production deployments do not silently seed the demo workspace. The SOD
// launch lanes set it explicitly via packaging.json env_defaults when demo
// data is needed (spec §14.3 step 6: "If FF_SEED_DEMO=1").
if (!process.env.FF_SEED_DEMO) {
  process.env.FF_SEED_DEMO = '0';
}

// Canonical spelling: the predicate below and run-executor's literal
// `FF_SEED_DEMO !== 'true' && !== '1'` loopback-exemption gate must never
// disagree about the same environment value. A case-variant spelling like
// 'TRUE' would seed the demo workspace at boot (index.ts) while the
// exemption—the gate the seeded workflows' `env.FF_APP_URL` http steps need,
// §8.8/§12—stays off, leaving a running demo whose workflows all fail with
// private_ip_blocked. Rewriting enabled spellings to '1' at import time
// keeps every reader consistent; both the server and the standalone worker
// import this module before any FF_SEED_DEMO consumer. (Function
// declarations hoist, so isDemoSeedEnabled is defined below this point.)
if (process.env.FF_SEED_DEMO !== '1' && isDemoSeedEnabled(process.env.FF_SEED_DEMO)) {
  process.env.FF_SEED_DEMO = '1';
}

/**
 * Demo-seed predicate (§4.4). Accepts ONLY '1' and 'true' (trimmed,
 * case-insensitive) — the two spellings the packaging contract and Node.js
 * boolean conventions use. 'yes'/'on'/''/undefined are deliberately false:
 * a value loose enough to seed a credential-disclosing demo account on a
 * typo is worse than a lane that needs its flag spelling corrected.
 */
export function isDemoSeedEnabled(raw?: string | null): boolean {
  const normalized = raw?.trim().toLowerCase();
  return normalized === '1' || normalized === 'true';
}

export interface DemoSettings {
  enabled: boolean;
  email: string;
  password: string;
}

/**
 * Resolve the demo identity from the environment at CALL time (per-test env
 * overrides and per-boot changes must not require a module reset).
 *
 * - email: FF_DEMO_EMAIL, falling back to demo@acme.test when unset, empty,
 *   or whitespace-only (trim-then-check — whitespace is never valid in an
 *   email). The value is trimmed and lowercased because the login route
 *   lowercases before querying; seeding a mixed-case address would create an
 *   account that cannot authenticate.
 * - password: FF_DEMO_PASSWORD, falling back to demo-pass-2026 only when
 *   unset or EXACTLY ''. Passwords are whitespace-significant, so a value of
 *   '   ' is preserved verbatim (intentional asymmetry with email).
 *
 * This module is the ONLY module that reads process.env.FF_DEMO_EMAIL /
 * process.env.FF_DEMO_PASSWORD; every consumer receives the resolved values
 * through getDemoSettings(). The resolved password is never logged.
 */
export function getDemoSettings(): DemoSettings {
  const rawEmail = process.env.FF_DEMO_EMAIL;
  const email = rawEmail && rawEmail.trim().length > 0 ? rawEmail.trim().toLowerCase() : 'demo@acme.test';
  const rawPassword = process.env.FF_DEMO_PASSWORD;
  const password = rawPassword === undefined || rawPassword === '' ? 'demo-pass-2026' : rawPassword;
  return { enabled: isDemoSeedEnabled(process.env.FF_SEED_DEMO), email, password };
}

/**
 * Resolve FF_APP_URL at runtime, using the actual listening port.
 *
 * Precedence:
 * 1. FF_APP_URL if already set (explicit operator override)
 * 2. APP_BASE_URL (SOD-provided public origin, §packaging.json env_var_names)
 * 3. http://localhost:{port} (portable default)
 *
 * Called from startServer() after the port has been resolved so the derived
 * URL always matches the actual listening port — not a hardcoded Dockerfile
 * default that may differ from the SOD-assigned port.
 */
export function resolveAppUrl(port: number): string {
  if (process.env.FF_APP_URL) {
    return process.env.FF_APP_URL;
  }
  if (process.env.APP_BASE_URL) {
    return process.env.APP_BASE_URL;
  }
  return `http://localhost:${port}`;
}
